on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test jira action
    steps:
      - name: Test
        id: test
        uses: Bondvet/link-jira-issue-action@main
        with:
          project-keys: EX,IN,BV
