on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test jira action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        id: test
        uses: ./
        with:
          project-keys: EX,IN,BV
